### ISSUE TITLE
CMake error on OpenCV set_target_properties

### ISSUE THREAD

**Issue by Minotaur-CN** [patrikhuber/superviseddescent#11]
Dear all,
 I build the code in this github, and find the cmake build error both on linux and Windows. Could help me to fix it ? Thanks very much!
PS: I used to build the previous one successfully。

Linux Error:
Centos +Cmake 3.3.0
![image](https://cloud.githubusercontent.com/assets/9798125/8668365/d42b592c-2a3c-11e5-86e0-bcb90f18da43.png)

Windows Error:
Windows 8.1+ VS2013+Cmake3.3.0
Cmake Error
![image](https://cloud.githubusercontent.com/assets/9798125/8668373/ef618252-2a3c-11e5-9a14-acf29797fc78.png)

That's very grateful to help me get though this bug.
Thanks very Much!

**Comment by patrikhuber** [comment]
Hi @Minotaur-CN,

Your second error on Windows definitely looks like a problem on your system. Try for example launching CMake from the VS command prompt or try the Win64 generator, or reinstalling VS. I don't think I can help with that issue.

The first one looks rather odd, I'll test with CMake 3.3. In the meantime, can you try with an older CMake? It could also be because I may have not tested it with the system-installed OpenCV. Also try just uncommenting that line, as long as you don't use the RelWithDebugInfo build, it doesn't matter.

**Comment by Minotaur-CN** [comment]
hi, @patrikhuber 
I find the linux part bug is due to the VMWARE. I used to build the code under the windows shared folder.Now, I build the code under the linux ext3 filesystem, that can be passed.
That error happened on the opencv build process.

Thanks for u time!

**Comment by YorkLeeSIAT** [comment]
@patrikhuber 
Hi,
duiring using your code rcr-train.cpp to train my own model,it corrupt for memory leak.I use win32 to compare code, why did you said" Try for example launching CMake from the VS command prompt or try the Win64 generator",will it  be wrong when use  Win32 generator?? ?

**Comment by patrikhuber** [comment]
Hi @YorkLeeSIAT,

It would be great if you could open a new issue next time, this is not at all related to this issue.

As for your problem: I never tried the 32-bit generator, I always use the 64-bit one, so 32-bit is not officially supported. That said, it should work fine, and if you're on the newest version, you also shouldn't have memory issues (>=3.5 GB can naturally be an issue on 32-bit) because it shouldn't use more than 0.5-2 GBs. 

If you can describe me what exactly you're doing, and what the error is, maybe I can help. Also a screenshot of the memory usage while running would be great.

**Comment by YorkLeeSIAT** [comment]
Hi @patrikhuber ,
Thanks for your code and answer.Yes ,win32 project will corrupt for finite memmory,Win64 works well.

**Comment by patrikhuber** [comment]
Great. Everything seems solved here, so I'll close the issue.

I strongly suspect though that there was no memory leak/corruption - probably you just ran out of memory. But it's hard to tell without knowing the error message.
