### ISSUE TITLE
Run project on Codeblock on Ubuntu

### ISSUE THREAD

**Issue by Krzef** [patrikhuber/superviseddescent#33]
Hi Patrik,

I'm trying to run and test your project under Codeblocks. Is that possible?
I've ran examples .cpp files in terminal but don't know how to run whole project in Codeblocks.

Can you help me on that?

**Comment by patrikhuber** [comment]
Hi Filip,

superviseddescent definitely runs on Ubuntu, on any Linux with a recent compiler in fact. I don't have any experience with Codeblocks. I suggest you check if CMake has a generator for Codeblocks. If not, Google may help. Otherwise you can also just write your own app in Codeblocks and then just include the superviseddescent headers (as it's a header-only library).

**Comment by Krzef** [comment]
Thanks, rebuild the project with cmake command using CodeBlocks option works well, I can open superviseddescent.cbp in Codeblocks and build the project but when I tried to run program - it doesn't do anything. 
I know that's weird and silly but:
How can I run a single program e.g. landmark detection.cpp in Codeblocks?

**Comment by patrikhuber** [comment]
Sorry, I've never used Codeblocks. Stackoverflow or something like that would be a more appropriate place for such kind of questions.

I'm closing since this is not a superviseddescent library issue.
