### ISSUE TITLE
Error Building in Visual Studio RC2015 on Windows 10

### ISSUE THREAD

**Issue by ghost** [patrikhuber/superviseddescent#48]
I have visual studio RC2015 on windows 10. I have downloaded Eigen 3.3, opencv3.2 (Since the 2.4.3 does not support visual studio RC2015), I downloaded boost 1_63 and the supervised descent project. I included the necessary directories in visual studio. 
When trying to build rcr-detect.cpp I got the following error:
C4244, 'initializing': conversion from 'double' to 'int', possible loss of data. 
Finally, what are the proper versions for Eigen, opencv, boost?
![capture](https://cloud.githubusercontent.com/assets/26584101/25500767/476ff914-2b5e-11e7-9bcf-19d31555ee9b.PNG)

**Comment by patrikhuber** [comment]
Sorry, I currently don't have the time to support the project properly. In any case I've used it with VS2015 RC before and it should work fairly well with all versions. It's probably only a very small fix.

You shouldn't use an RC version of VS anyway by the way since the final of both 2015 and 2017 are out. If you want OpenCV 2.4.x for VS2015, try 2.4.13, I think it supports 2015. In any case you can try with the versions specified in the [readme](https://github.com/patrikhuber/superviseddescent). But as mentioned it should be very small fixes to make it work with any compiler since the code is pretty modern and cross-platform.

**Comment by ghost** [comment]
I have downloaded opencv 2.4.13, but still getting the following errors:
![capture](https://cloud.githubusercontent.com/assets/26584101/25533346/5bbf9eb0-2bfe-11e7-8c71-449fa4f25efe.PNG)
Thank for help!!

**Comment by patrikhuber** [comment]
I'm closing this. I think this was a problem with the users's warning/error settings in VS, and had nothing to do with `superviseddescent`. One way to resolve it is probably defining what the error says.
